### ISSUE TITLE
Gregorian calendar has 365.2425 days per year

### ISSUE THREAD

**Issue by barrycarter** [a-p-jo/secondtime#1]
In our current Gregorian calendar, there are 365.2425 days, not 365.25. You should either correct for this or at least mention in the code you are using a non-Greogrian calendar.

**Comment by a-p-jo** [comment]
Thank you very much for opening this issue!

Yeah, the code says a year is `31557600` seconds, which is 365.25 days and is the unit used in the Julian calendar rather than the Gregorian one. This needs fixing; I hadn't quite realized this before. 

On further research, I also discovered [solar time](https://en.wikipedia.org/wiki/Solar_time#Mean_solar_time) and the concept of the [mean tropical year](https://en.wikipedia.org/wiki/Tropical_year). 

Would you prefer the tool to use the Gregorian calendar year (365.2425 days) or the mean tropical year (365.24219 days)?

**Comment by a-p-jo** [comment]
@barrycarter In the latest commits, I've added the ability to select among half a dozen year types and the default is the gregorian year. This can be configured in `config.h`.

Let me know if this fixes the issue.

**Comment by barrycarter** [comment]
Looks great, thanks!
